// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdofye8UWft9ar-Zmu5dowGuXcElFUJrE',
    appId: '1:171978070585:web:81ebf04bc3677796684be8',
    messagingSenderId: '171978070585',
    projectId: 'activityrecognitionapp-5a32a',
    authDomain: 'activityrecognitionapp-5a32a.firebaseapp.com',
    databaseURL: 'https://activityrecognitionapp-5a32a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'activityrecognitionapp-5a32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshQE00xVl8ESOFAo9UYWuruxYR3ixSws',
    appId: '1:171978070585:android:1f90597d9c8f1877684be8',
    messagingSenderId: '171978070585',
    projectId: 'activityrecognitionapp-5a32a',
    databaseURL: 'https://activityrecognitionapp-5a32a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'activityrecognitionapp-5a32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MKKVbFgAzsB-PEfAcc-G_ncpxvWixeM',
    appId: '1:171978070585:ios:ba1e20173f08f273684be8',
    messagingSenderId: '171978070585',
    projectId: 'activityrecognitionapp-5a32a',
    databaseURL: 'https://activityrecognitionapp-5a32a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'activityrecognitionapp-5a32a.appspot.com',
    iosClientId: '171978070585-75b0sqjfcm94mb96qs03vl356jp9id8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.recognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1MKKVbFgAzsB-PEfAcc-G_ncpxvWixeM',
    appId: '1:171978070585:ios:ba1e20173f08f273684be8',
    messagingSenderId: '171978070585',
    projectId: 'activityrecognitionapp-5a32a',
    databaseURL: 'https://activityrecognitionapp-5a32a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'activityrecognitionapp-5a32a.appspot.com',
    iosClientId: '171978070585-75b0sqjfcm94mb96qs03vl356jp9id8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.recognition',
  );
}
